version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npx semantic-release
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: |
          git config user.email "leonard.hertel@gmail.com"
          git config user.name "herteleo"
      - run: npm ci
      - run: npm run build
      - run: npx gh-pages --dotfiles --repo https://${GITHUB_TOKEN}@github.com/pigmentapp/getpigment.app.git --message "[skip ci] Updates" --dist public

workflows:
  version: 2
  lint_and_release:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - gh-pages
      - release:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
                - dev
      - deploy:
          requires:
            - release
          filters:
            branches:
              only:
                - master
